apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
spec:
  replicas: 2
  selector:
    matchLabels:
      role: mysql
  template:
    metadata:
      labels:
        role: mysql
    spec:
      containers:
      - name: mysql
        image: mysql:latest
        resources:
          requests:
            cpu: 10m
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: mysql
        - name: MYSQL_PORT
          value: "3306"
        - name: MYSQL_USER
          value: username
        - name: MYSQL_PASSWORD
          value: password
